export const MAX_PRICE_IN_CENTS = 1_000_000;
export const MAX_ORDER_ITEM_QUANTITY = 99;
export const MAX_ORDER_TOTAL_IN_CENTS = 10_000_000;
export const FEATURED_PRODUCTS_LIMIT = 10;
export const MOST_ORDERED_PRODUCTS_LIMIT = 5;
export const MAX_IMAGE_URL_LENGTH = 2048;
